Connect-VIServer -Server <servername> -Protocol https -User root -Password <insertPassword>

$Datastores = Get-Datastore "LUN_NAME"
$server = Get-VMHost
$numsamples ="15"

function GetAvgStat($server,$vm,$ds,$samples,$stat){
	# number of samples = x time
	# 180 = 60min
	# 90 = 30min
	# 45 = 15min
	# 15 = 5min
	# 3 = 1min
	# 1 = 20sec (.33 min)

	# identify device id for datastore
	$myDatastoreID = ((Get-Datastore $ds -server $server) | Get-View).info.vmfs.extent[0].diskname
	
	# gather iops generated by vm
	$rawVMStats = get-stat -entity	(get-vm $vm -server $server) -stat $stat -maxSamples $samples
	$results = @()
	
	foreach ($stat in $rawVMStats) {
		if ($stat.instance.Equals($myDatastoreID)) {
			$results += $stat.Value
		}
	}
	
	$totalIOPS = 0
	foreach ($res in $results) {
		$totalIOPS += $res	
	}
	
	return [int] ($totalIOPS/$samples/20)
}

$IOPSReport = @()

foreach ($datastore in $datastores) {

  # Grab datastore and find VMs on that datastore
  $datastore = get-datastore -Name "LUN_NAME"
  $myVMs = Get-VM -Datastore "LUN_NAME" | Where {$_.PowerState -eq "PoweredOn"}
  
  # Gather current IO snapshot for each VM
  $dataArray = @()
  foreach ($vm in $myVMs) {
  	$data = “” | Select "VM", "Interval (minutes)", "Avg Write IOPS", "Avg Read IOPS"
  	$data."VM" = $vm.name
  	$data."Interval (minutes)" = ($numsamples*20)/60
  	$data."Avg Write IOPS" = GetAvgStat -vmhost $vm.host.name -vm $vm.name -ds $datastore -samples $numsamples -stat disk.numberWrite.summation
  	$data."Avg Read IOPS" = GetAvgStat -vmhost $vm.host.name -vm $vm.name -ds $datastore -samples $numsamples -stat disk.numberRead.summation
  	$dataArray += $data
  }
  
  # Do something with the array of data
  $IOPSReport += $dataArray

}
$IOPSReport
$IOPSReport | Export-CSV c:\scripts\IOPSReport.csv -NoType
